#!/bin/bash

declare -a repos=(
  "homelab-devops"
  "dotfiles"
  "realtycoon"
  "adventofcode2022"
  "realtycoon2"
  "notes"
  "adventofcode_ex"
  "phoenix-quest"
  "space-transport"
  "space-race"
  "side-scrolling-war2"
  "side-scrolling-war"
  "dungeon-maker-roguelike"
  "dwarf-fortress-saves"
  "space-mm"
  "memex"
  "procedural_fantasy_wikipedia"
  "goby"
  "world-history-generator"
  "heroes-and-castles"
  "space-tycoon"
  "snailpark"
  "polkashop"
  "kg-vikings"
  "realgame"
  "hungry-waffle"
  "squirrel-life"
  "rover-ld39"
  "nature-sim"
  "LameStrategy"
  "UnderPressure"
  "HexRails"
  "rastgen"
  "paranoid-social"
  "craftish"
  "printable-road-maps"
  "pick"
  "explore-space"
  "seine"
  "fusscms"
  "gopoints"
  "invisible_ink"
  "hateaos_browser"
  "fuss_engine"
  "codefuss"
  "ngj2012"
  "xnaheist"
  "ElephantMarkdown"
  "newciv"
  "zombie_platform"
  "beacoder"
  "shackle"
  "jscastlebuilder"
  "sidescroller"
)

for repo in "${repos[@]}"
do
  if [ ! -d "$repo" ] ; then
    git clone git@github.com:martinvium/$repo.git $repo
  else
    echo "Skipping $repo already cloned"
  fi
done
