#!/bin/bash

declare -a repos=(
  "martinvium/homelab-devops"
  "martinvium/dotfiles"
  "martinvium/realtycoon"
  "martinvium/adventofcode2022"
  "martinvium/realtycoon2"
  "martinvium/notes"
  "martinvium/adventofcode_ex"
  "martinvium/phoenix-quest"
  "martinvium/space-transport"
  "martinvium/space-race"
  "martinvium/side-scrolling-war2"
  "martinvium/side-scrolling-war"
  "martinvium/dungeon-maker-roguelike"
  "martinvium/dwarf-fortress-saves"
  "martinvium/space-mm"
  "martinvium/memex"
  "martinvium/procedural_fantasy_wikipedia"
  "martinvium/goby"
  "martinvium/world-history-generator"
  "martinvium/heroes-and-castles"
  "martinvium/space-tycoon"
  "martinvium/snailpark"
  "martinvium/polkashop"
  "martinvium/kg-vikings"
  "martinvium/realgame"
  "martinvium/hungry-waffle"
  "martinvium/squirrel-life"
  "martinvium/rover-ld39"
  "martinvium/nature-sim"
  "martinvium/LameStrategy"
  "martinvium/UnderPressure"
  "martinvium/HexRails"
  "martinvium/rastgen"
  "martinvium/paranoid-social"
  "martinvium/craftish"
  "martinvium/printable-road-maps"
  "martinvium/pick"
  "martinvium/explore-space"
  "martinvium/seine"
  "martinvium/fusscms"
  "martinvium/gopoints"
  "martinvium/invisible_ink"
  "martinvium/hateaos_browser"
  "martinvium/fuss_engine"
  "martinvium/codefuss"
  "martinvium/ngj2012"
  "martinvium/xnaheist"
  "martinvium/ElephantMarkdown"
  "martinvium/newciv"
  "martinvium/zombie_platform"
  "martinvium/beacoder"
  "martinvium/shackle"
  "martinvium/jscastlebuilder"
  "martinvium/sidescroller"
  "The-Heroes-Journey-EQEMU/quests"
  "The-Heroes-Journey-EQEMU/Server"
  "The-Heroes-Journey-EQEMU/thj-wiki"
  "The-Heroes-Journey-EQEMU/eqemupatcher-test"
  "The-Heroes-Journey-EQEMU/eqemupatcher"
  "The-Heroes-Journey-EQEMU/eqdb"
  "The-Heroes-Journey-EQEMU/thj-patcher"
  "The-Heroes-Journey-EQEMU/thj-launcher"
  "The-Heroes-Journey-EQEMU/maps"
  "The-Heroes-Journey-EQEMU/PrymeView"
)

for repo in "${repos[@]}"
do
  if [ ! -d "$repo" ] ; then
    mkdir -p $repo
    git clone git@github.com:$repo.git $repo
  else
    echo "Skipping $repo already cloned"
  fi
done
